import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Footer from "@/components/Footer";
import MenuSection from "@/components/MenuSection";
import HoursAndContactSection from "@/components/HoursAndContactSection";
import CareerSection from "@/components/CareerSection";
import OurStorySection from "@/components/OurStorySection";
import GiftCardSection from "@/components/GiftCardSection";
import ChristmasSection from "@/components/ChristmasSection";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid h-full grid-cols-1 bg-marble bg-repeat-round">
        <Navbar />

        <Header />
        <GiftCardSection />
        <OurStorySection />
        <CareerSection />
        <HoursAndContactSection />
        <MenuSection />

        <Footer />
      </div>
    </>
  );
}
